apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
{{- range .Values.awsAuthConfig.mapRoles }}
    - rolearn: "{{ .rolearn }}"
      username: "{{ .username }}"
      groups:
{{ toYaml .groups | indent 8 }}
{{- end }}
